[2024-10-21T01:07:45.064+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: twitch_data_pipeline.extract_stream_data manual__2024-10-21T01:07:43.562521+00:00 [queued]>
[2024-10-21T01:07:45.078+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: twitch_data_pipeline.extract_stream_data manual__2024-10-21T01:07:43.562521+00:00 [queued]>
[2024-10-21T01:07:45.078+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-10-21T01:07:45.078+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2024-10-21T01:07:45.078+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-10-21T01:07:45.098+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_stream_data> on 2024-10-21 01:07:43.562521+00:00
[2024-10-21T01:07:45.112+0000] {standard_task_runner.py:55} INFO - Started process 2710 to run task
[2024-10-21T01:07:45.116+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitch_data_pipeline', 'extract_stream_data', 'manual__2024-10-21T01:07:43.562521+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpxxk294qd']
[2024-10-21T01:07:45.117+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask extract_stream_data
[2024-10-21T01:07:45.199+0000] {task_command.py:389} INFO - Running <TaskInstance: twitch_data_pipeline.extract_stream_data manual__2024-10-21T01:07:43.562521+00:00 [running]> on host fba2d95bf80f
[2024-10-21T01:07:45.307+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=leo-coltri
AIRFLOW_CTX_DAG_ID=twitch_data_pipeline
AIRFLOW_CTX_TASK_ID=extract_stream_data
AIRFLOW_CTX_EXECUTION_DATE=2024-10-21T01:07:43.562521+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-21T01:07:43.562521+00:00
[2024-10-21T01:07:45.325+0000] {conn.py:1532} WARNING - DNS lookup failed for broker:29092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-21T01:07:45.325+0000] {conn.py:316} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-10-21T01:07:45.325+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-21T01:07:45.335+0000] {conn.py:1532} WARNING - DNS lookup failed for broker:29092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-21T01:07:45.335+0000] {conn.py:316} ERROR - DNS lookup failed for broker:29092 (AddressFamily.AF_UNSPEC)
[2024-10-21T01:07:45.335+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/data_extraction.py", line 17, in extract_stream_data
    producer = create_kafka_producer()
  File "/opt/airflow/dags/scripts/data_extraction.py", line 9, in create_kafka_producer
    return KafkaProducer(bootstrap_servers=['broker:29092'], max_block_ms=5000)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 383, in __init__
    **self.config)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-10-21T01:07:45.349+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=twitch_data_pipeline, task_id=extract_stream_data, execution_date=20241021T010743, start_date=20241021T010745, end_date=20241021T010745
[2024-10-21T01:07:45.365+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 10 for task extract_stream_data (NoBrokersAvailable; 2710)
[2024-10-21T01:07:45.408+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-10-21T01:07:45.436+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
